import Image from 'next/image';

export const metadata = {
  title: 'Tela Login',
  description: 'Generated by create next app',
};

export default function Home() {
  function login() {
    window.location.href = '/page/funcionario/';
  }

  return (
    <main className='flex min-h-screen flex-col items-center justify-between p-24 bg-gray-100'>
      <section>
        <span className='text-3xl font-bold'>Archip</span>
      </section>

      <section className='flex flex-col gap-7'>
        <a href='/page/funcionario/' className='bg-slate-200 px-6 py-2 flex items-center gap-4 rounded-lg font-semibold'>
          <Image src='./Google__G__logo.svg' width='30' height='30' alt='' />
          Google
        </a>

        <a href='/page/funcionario/' className='bg-slate-200 px-6 py-2 flex items-center gap-4 rounded-lg font-semibold'>
          <Image src='./Icloud.svg' width='30' height='30' alt='' />
          Apple
        </a>
      </section>

      <section>
        <span>Escolha uma opção para fazer login na sua conta</span>
      </section>
    </main>
  );
}
